from pyvis.network import Network

net = Network(height="70%", width="100%", directed=True, layout=True)

net.add_node("h1", hidden=True, physics=False)
net.add_node("h2", hidden=True, physics=False)
net.add_node("AST_NODE_PROGRAM_0xa47430", title=r"AST_NODE_PROGRAM_0xa47430 {<br \> &emsp;No information here!<br \>}")

net.add_edge("AST_NODE_PROGRAM_0xa47430", "h1", hidden=True, physics=False)
net.add_edge("AST_NODE_PROGRAM_0xa47430", "h2", hidden=True, physics=False)

net.add_node("AST_NODE_MODULEDECLARATION_0xa47490", title=r"AST_NODE_MODULEDECLARATION_0xa47490 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_PROGRAM_0xa47430", "AST_NODE_MODULEDECLARATION_0xa47490")
net.add_node("AST_NODE_MODULELIST_0xa47550", title=r"AST_NODE_MODULELIST_0xa47550 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_PROGRAM_0xa47430", "AST_NODE_MODULELIST_0xa47550")
net.add_node("AST_NODE_MODULELIST_0xa4a900", title=r"AST_NODE_MODULELIST_0xa4a900 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_PROGRAM_0xa47430", "AST_NODE_MODULELIST_0xa4a900")
net.add_node("AST_NODE_MODULELIST_0xa4c4e0", title=r"AST_NODE_MODULELIST_0xa4c4e0 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_PROGRAM_0xa47430", "AST_NODE_MODULELIST_0xa4c4e0")
net.add_node("AST_NODE_MODULEDECLARATION_0xa47490", title=r"AST_NODE_MODULEDECLARATION_0xa47490 {<br \> &emsp;No information here!<br \>}")
net.add_node("AST_NODE_LEAF_0xa474f0", title=r"AST_NODE_LEAF_0xa474f0 {<br \> &emsp;type: AST_LEAF_ID<br \>&emsp;lex: NULL<br \>}")
net.add_edge("AST_NODE_MODULEDECLARATION_0xa47490", "AST_NODE_LEAF_0xa474f0")
net.add_node("AST_NODE_MODULELIST_0xa47550", title=r"AST_NODE_MODULELIST_0xa47550 {<br \> &emsp;No information here!<br \>}")
net.add_node("AST_NODE_MODULE_0xa475b0", title=r"AST_NODE_MODULE_0xa475b0 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_MODULELIST_0xa47550", "AST_NODE_MODULE_0xa475b0")
net.add_node("AST_NODE_MODULELIST_0xa4a900", title=r"AST_NODE_MODULELIST_0xa4a900 {<br \> &emsp;No information here!<br \>}")
net.add_node("AST_NODE_STATEMENT_0xa4a9a0", title=r"AST_NODE_STATEMENT_0xa4a9a0 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_MODULELIST_0xa4a900", "AST_NODE_STATEMENT_0xa4a9a0")
net.add_node("AST_NODE_MODULELIST_0xa4c4e0", title=r"AST_NODE_MODULELIST_0xa4c4e0 {<br \> &emsp;No information here!<br \>}")
net.add_node("AST_NODE_MODULE_0xa4c580", title=r"AST_NODE_MODULE_0xa4c580 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_MODULELIST_0xa4c4e0", "AST_NODE_MODULE_0xa4c580")
net.add_node("AST_NODE_LEAF_0xa474f0", title=r"AST_NODE_LEAF_0xa474f0 {<br \> &emsp;type: AST_LEAF_ID<br \>&emsp;lex: NULL<br \>}")
net.add_node("AST_NODE_MODULE_0xa475b0", title=r"AST_NODE_MODULE_0xa475b0 {<br \> &emsp;No information here!<br \>}")
net.add_node("AST_NODE_LEAF_0xa47610", title=r"AST_NODE_LEAF_0xa47610 {<br \> &emsp;type: AST_LEAF_ID<br \>&emsp;lex: NULL<br \>}")
net.add_edge("AST_NODE_MODULE_0xa475b0", "AST_NODE_LEAF_0xa47610")
net.add_node("AST_NODE_INPUTLIST_0xa476b0", title=r"AST_NODE_INPUTLIST_0xa476b0 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_MODULE_0xa475b0", "AST_NODE_INPUTLIST_0xa476b0")
net.add_node("AST_NODE_OUTPUTLIST_0xa47c00", title=r"AST_NODE_OUTPUTLIST_0xa47c00 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_MODULE_0xa475b0", "AST_NODE_OUTPUTLIST_0xa47c00")
net.add_node("AST_NODE_STATEMENT_0xa47e00", title=r"AST_NODE_STATEMENT_0xa47e00 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_MODULE_0xa475b0", "AST_NODE_STATEMENT_0xa47e00")
net.add_node("AST_NODE_STATEMENT_0xa4a9a0", title=r"AST_NODE_STATEMENT_0xa4a9a0 {<br \> &emsp;No information here!<br \>}")
net.add_node("AST_NODE_DECLARESTMT_0xa4aa40", title=r"AST_NODE_DECLARESTMT_0xa4aa40 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_STATEMENT_0xa4a9a0", "AST_NODE_DECLARESTMT_0xa4aa40")
net.add_node("AST_NODE_STATEMENT_0xa4ae30", title=r"AST_NODE_STATEMENT_0xa4ae30 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_STATEMENT_0xa4a9a0", "AST_NODE_STATEMENT_0xa4ae30")
net.add_node("AST_NODE_MODULE_0xa4c580", title=r"AST_NODE_MODULE_0xa4c580 {<br \> &emsp;No information here!<br \>}")
net.add_node("AST_NODE_LEAF_0xa4c630", title=r"AST_NODE_LEAF_0xa4c630 {<br \> &emsp;type: AST_LEAF_ID<br \>&emsp;lex: NULL<br \>}")
net.add_edge("AST_NODE_MODULE_0xa4c580", "AST_NODE_LEAF_0xa4c630")
net.add_node("AST_NODE_INPUTLIST_0xa4c6d0", title=r"AST_NODE_INPUTLIST_0xa4c6d0 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_MODULE_0xa4c580", "AST_NODE_INPUTLIST_0xa4c6d0")
net.add_node("AST_NODE_STATEMENT_0xa4cc20", title=r"AST_NODE_STATEMENT_0xa4cc20 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_MODULE_0xa4c580", "AST_NODE_STATEMENT_0xa4cc20")
net.add_node("AST_NODE_LEAF_0xa47610", title=r"AST_NODE_LEAF_0xa47610 {<br \> &emsp;type: AST_LEAF_ID<br \>&emsp;lex: NULL<br \>}")
net.add_node("AST_NODE_INPUTLIST_0xa476b0", title=r"AST_NODE_INPUTLIST_0xa476b0 {<br \> &emsp;No information here!<br \>}")
net.add_node("AST_NODE_LEAF_0xa47760", title=r"AST_NODE_LEAF_0xa47760 {<br \> &emsp;type: AST_LEAF_ID<br \>&emsp;lex: NULL<br \>}")
net.add_edge("AST_NODE_INPUTLIST_0xa476b0", "AST_NODE_LEAF_0xa47760")
net.add_node("AST_NODE_ARRAY_0xa47800", title=r"AST_NODE_ARRAY_0xa47800 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_INPUTLIST_0xa476b0", "AST_NODE_ARRAY_0xa47800")
net.add_node("AST_NODE_INPUTLIST_0xa47a00", title=r"AST_NODE_INPUTLIST_0xa47a00 {<br \> &emsp;No information here!<br \>}")
net.add_edge("AST_NODE_INPUTLIST_0xa476b0", "AST_NODE_INPUTLIST_0xa47a00")
net.add_node("AST_NODE_OUTPUTLIST_0xa47c00", title=r"AST_NODE_OUTPUTLIST_0xa47c00 {<br \> &emsp;No information here!<br \>}")
net.add_node("AST_NODE_LEAF_0xa47cb0", title=r"AST_NODE_LEAF_0xa47cb0 {<br \> &emsp;type: AST_LEAF_ID<br \>&emsp;lex: NULL<br \>}")
net.add_edge("AST_NODE_OUTPUTLIST_0xa47c00", "AST_NODE_LEAF_0xa47cb0")
